### ISSUE TITLE
fluent-plugin-s3 just hangs (stops) and don't work.

### ISSUE THREAD

**Issue by myungjae1** [fluent/fluent-plugin-s3#183]
Hi,

Thanks for all your effort first.
I'm really awaiting the official release of fluent-plugin-s3 v1.0.0!

I just wanna let you know a kindof bug that I've noticed recently.

# What I want
- fluent-plugin-s3 keeps working (flushing to S3) without stop.

# What I am currently experiencing
- fluent-plugin-s3 just stops working abruptly. No flushing to S3.

# Weird things I've noticed
- sometimes (**not always**) there are chunk metadata whose size is 0 or about half of other normal metadata.
- sometimes (**not always**) there are error log which say like below.
```
2017-02-10 12:42:37 +0900 [error]: unexpected error while checking flushed chunks. ignored. error_class=NoMethodError error="undefined method `<' for nil:NilClass"
```

# Environment
- AWS EC2
- Ubuntu 16.04
- Dockerized fluentd (Alpine Linux)
- Docker version 1.12.2
- fluentd v0.14.11 (installed by rubygem)
- fluent-plugin-s3 v1.0.0.rc2 (installed by rubygem)

# Metrics I wanna show you

![log-archive-pixelated](https://cloud.githubusercontent.com/assets/1889939/22919439/3dd06bfa-f2d3-11e6-9382-0694665a808b.png)

I pixelated private information.

- There are total 10 fluentd nodes who flush to S3.
- 2 nodes among them stoped working abruptly. You can see Red and Orange color lines in the screenshot.
- fluentd buffers of 2 nodes keep same value for long time. (No flush to S3)
- Almost zero write ops to disk. (No chunking to file)
- Almost zero network transmitted (No flush to S3)

# fluentd configs
```
<match {{my_tag}}>
  @type s3

  <instance_profile_credentials>
  </instance_profile_credentials>

  s3_region ap-northeast-2
  s3_bucket {{my_s3_bucket}}
  s3_object_key_format %{path}/%{time_slice}_%{uuid_flush}.%{file_extension}
  path ${_role}/ec2/${_instance_id}/${_application}
  time_slice_format %Y/%m/%d/%H:%M

  store_as text
  format json
  include_time_key true
  time_key timestamp

  <buffer _service,_role,_instance_id,_application,time>
    @type file
    path {{my_buffer_path}}

    flush_at_shutdown true
    flush_thread_count 8
    timekey 300
    timekey_wait 15 
  </buffer>
</match>
```

**Comment by repeatedly** [comment]
It seems the bug of fluentd's buffer, not s3 plugin.
I will work on it but I don't recommend v0.14 on the production.

**Comment by repeatedly** [comment]
BTW, no error logs in fluentd log?

**Comment by breadmj** [comment]
Sometimes (**not always**) there are error logs like below. No warning logs. Just those error logs. (Log level of fluentd is currently set to `info`)
```
2017-02-10 12:42:37 +0900 [error]: unexpected error while checking flushed chunks. ignored. error_class=NoMethodError error="undefined method `<' for nil:NilClass"
```

What I want to emphasize here is this; If error log happens, then fluent-plugin-s3 stops working. But the reverse is not true. fluent-plugin-s3 sometimes stops working even if there is no error/warn log.

**Comment by breadmj** [comment]
There is only one warn log like this.
This warn log happens when the fluentd starts up.

```
2017-02-15 10:48:13 +0900 [warn]: many chunk keys specified, and it may cause too many chunks on your system.
```

**Comment by repeatedly** [comment]
I'm now working on fixing this problem.
Could you tell me more detailed of your traffic?
How much volume and could you show me log example without sensitive data?
I want to reproduce this problem on our test environment.

**Comment by breadmj** [comment]
Hi @repeatedly, sorry for late.

**Average traffic**
1.5K logs per sec.

**Size in byte per log**
It varies on log message but about 500~1500 Byte per log.

**Log Example**
```json
{
  "version":"1.1",
  "short_message":"this is a log message!",
  "timestamp":"2017-01-01T09:00:00+09:00",
  "host":"myhostname",
  "_instance_id":"i-012345679abc",
  "_service":"myservice",
  "_role":"myrole",
  "_application":"myapp",
  "_seq_id":"1483228800.859510183",
}
```

Hope this helps.

**Comment by repeatedly** [comment]
Thanks!
I use these setting for debugging problem.

**Comment by bartelsb** [comment]
We are also experiencing this problem at my organization. In our case, it seems to _always_ be accompanied by 0 byte metadata files and 0 byte log files. We haven't determined which of the two causes the plugin to actually hang, or if both can do this. 

I believe we're using v1.1.3 of the plugin.

**Comment by repeatedly** [comment]
How about latest fluentd and fluent-plugin-s3? still happens?

**Comment by bartelsb** [comment]
We'll be upgrading to that shortly (we hope). I can report back if we're still seeing it after upgrading.

**Comment by snypelife** [comment]
I seem to be encountering this.  We are currently targeting ubuntu auth logs explicitly, and it seems like if there is nothing to ship fluentd gets stuck and won't ship anything after this happens. 

## Basic info
- AWS EC2
- Ubuntu 18.04
- Dockerized fluentd
- Docker version 19.03.13
- fluentd:edge
- fluent-plugin-s3:1.5.1

## fluentd config

I use `copy` so that I can confirm what I see in stdout is ending up in the S3 bucket.
```
<match system.{auth,auth*}.**>
  @type copy

  <store>
    @type s3
    s3_bucket [BUCKET_NAME]
    s3_region [AWS_REGION]
    store_as gzip
    path "#{ENV['ENV']}/#{ENV['NAME']}/#{ENV['aws_instance_id']}"
    s3_object_key_format %{path}/audit_%Y%m%d_%H%M_%{index}.%{file_extension}

    <instance_profile_credentials>
    </instance_profile_credentials>

    <buffer tag,time>
      @type file
      path /var/log/fluent/s3
      timekey 600 # 10 minute partition
      timekey_wait 1m
      timekey_use_utc true # use utc
      chunk_limit_size 256m
    </buffer>
  </store>

  <store>
    @type stdout
  </store>
</match>
```

## Error encountered
`2021-03-12 15:28:18 +0000 [warn]: #0 failed to flush the buffer. retry_time=11 next_retry_seconds=2021-03-12 15:44:57 334544029932425113/858993459200000000 +0000 chunk="5bd5829d650a86a94a0c539d3dfd66ed" error_class=Aws::S3::Errors::Forbidden error="Aws::S3::Errors::Forbidden"`

**Comment by snypelife** [comment]
Poking around more, I'm wondering if this issue is related to https://github.com/fluent/fluent-plugin-s3/issues/92? testing it out to confirm.

**Comment by snypelife** [comment]
Yes that appears to have been the cause for me. Please ignore my comment, and sorry for the trouble.
